backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "key", name: "key", widget: "hidden", default: "blog-post" }
      - { label: "Hero Image", name: "heroImage", widget: image }
      - { label: "Hero Image (alt text)", name: "heroImageAlt", widget: string }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Sub Title", name: "subTitle", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - { label: "key", name: "key", widget: "hidden", default: "home" }
          - label: "Call to action"
            name: "callToAction"
            widget: "object"
            fields:
              - {
                  label: "Input placeholder text",
                  name: "ctaPlaceholder",
                  widget: "string",
                  defaut: "youremailaddress@isawesome.com",
                }
              - {
                  label: "Button label",
                  name: "ctaButtonLabel",
                  widget: "string",
                }
          - label: "Hero"
            name: "hero"
            widget: "object"
            fields:
              - { label: "Image", name: "heroImage", widget: "image" }
              - {
                  label: "Title",
                  name: "heroTitle",
                  widget: "string",
                  default: "Love yourself first",
                }
              - {
                  label: "Sub-title",
                  name: "heroSubTitle",
                  widget: "string",
                  default: null,
                }
          - label: "Introduction"
            name: "introduction"
            widget: "object"
            fields:
              - { label: "Title", name: "introTitle", widget: "string" }
              - {
                  label: "Description",
                  name: "introDescription",
                  widget: "text",
                }
              - label: "Button"
                name: "introAction"
                widget: "object"
                fields:
                  - { label: "Label", name: "actionLabel", widget: "text" }
                  - {
                      label: "Go to page",
                      name: actionRoute,
                      widget: "select",
                      options: ["about", "blog", "services", "contact"],
                    }
          - label: "Testimonials"
            name: "testimonials"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "testimonialTitle",
                  widget: "string",
                  default: "What people are saying",
                }
              - label: "Entries"
                name: "testimonialEntries"
                widget: "list"
                fields:
                  - {
                      label: "Client Image",
                      name: "clientImage",
                      widget: "image",
                    }
                  - {
                      label: "Client Type",
                      name: "clientType",
                      widget: "string",
                    }
                  - {
                      label: "Client Location",
                      name: "clientLocation",
                      widget: "string",
                    }
                  - {
                      label: "Client Quote",
                      name: "clientQuote",
                      widget: "string",
                    }
          - label: "Method"
            name: "method"
            widget: "object"
            fields:
              - {
                  label: "Title",
                  name: "methodTitle",
                  widget: "string",
                  default: "My Methodology",
                }
              - label: "steps"
                name: "methodSteps"
                widget: "list"
                fields:
                  - { label: "Label", name: "label", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
                  - {
                      label: "Description",
                      name: "description",
                      widget: "text",
                    }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - { label: "key", name: "key", widget: "hidden", default: "home" }
          - label: "Main"
            name: "main"
            widget: "object"
            fields:
              - { label: "Title", name: "mainTitle", widget: "string" }
              - { label: "Blurb", name: "mainBlurb", widget: "text" }
              - label: "Background Image"
                name: "mainImage"
                widget: "object"
                fields:
                  - { label: "Img", name: "imgLocation", widget: "image" }
                  - {
                      label: "Img alternate text",
                      name: "imgAlt",
                      widget: "string",
                      hint: "This text will display if the image is not found",
                    }
                  - {
                      label: "Background image (x position)",
                      name: "imgXPosition",
                      widget: "number",
                      default: 0,
                      valueType: "int",
                      ? s
                        min
                      : 0,
                      max: 100,
                      step: 1,
                    }
                  - {
                      label: "Background image (y position)",
                      name: "imgYPosition",
                      default: 0,
                      valueType: "int",
                      min: 0,
                      max: 100,
                      step: 1,
                    }
                  - {
                      label: "Background image (height)",
                      name: "imgHeight",
                      widget: "number",
                      default: 700,
                    }
          - label: "Overview"
            name: "overview"
            widget: "object"
            fields:
              - { label: "Title", name: "overviewTitle", widget: "string" }
              - { label: "Blurb", name: "overviewBlurb", widget: "markdown" }

          - label: "Detail"
            name: "detail"
            widget: "object"
            fields:
              - { label: "Title", name: "detailTitle", widget: "string" }
              - {
                  label: "Avatar Image",
                  name: "detailAvatarImage",
                  widget: "image",
                }
              - { label: "Blurb", name: "detailBlurb", widget: "markdown" }

          - label: "Call to Action"
            name: "callToAction"
            widget: "object"
            fields:
              - { label: "Title", name: "ctaTitle", widget: "string" }
              - { label: "Blurb", name: "ctaBlurb", widget: "text" }
              - {
                  label: "Input Placeholder Text",
                  name: "catInputPlaceholder",
                  widget: "string",
                  default: "youremail@awesome.com",
                }
              - {
                  label: "Input Button Label",
                  name: "ctaButtonLabel",
                  widget: "string",
                  default: "Gimmie that wisdom",
                }

      - file: "src/pages/services/index.mx"
        label: "Services"
        name: "services"
        fields:
          - { label: "key", name: "key", widget: "hidden", default: "services" }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              default: "services",
            }
